# Generated by Django 6.0.5 on 2026-05-19 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersed", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Профіль", "verbose_name_plural": "Профілі"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Адреса"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Місто"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Поштовий індекс"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата народження"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=True, verbose_name="Email сповіщення"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Чоловіча"), ("F", "Жіноча"), ("O", "Інше")],
                max_length=1,
                null=True,
                verbose_name="Стать",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="newsletter_subscription",
            field=models.BooleanField(default=False, verbose_name="Підписка на новини"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Про себе"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
    ]
