# Generated by Django 6.0.5 on 2026-05-19 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Назва кольору")),
                (
                    "code",
                    models.CharField(
                        help_text="HEX код кольору, наприклад #FF0000",
                        max_length=7,
                        verbose_name="HEX код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Колір",
                "verbose_name_plural": "Кольори",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=10, unique=True, verbose_name="Розмір"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Порядок сортування"),
                ),
            ],
            options={
                "verbose_name": "Розмір",
                "verbose_name_plural": "Розміри",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("U", "Унісекс"),
                    ("M", "Чоловічий"),
                    ("F", "Жіночий"),
                    ("K", "Дитячий"),
                ],
                default="U",
                max_length=1,
                verbose_name="Стать",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(default=False, verbose_name="Хіт продажів"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Головне зображення"),
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shopee.color",
                verbose_name="Доступні кольори",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shopee.size",
                verbose_name="Доступні розміри",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1⭐"),
                            (2, "2⭐"),
                            (3, "3⭐"),
                            (4, "4⭐"),
                            (5, "5⭐"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оцінка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Коментар")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Схвалено"),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True, null=True, verbose_name="Відповідь адміністратора"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shopee.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
    ]
