# Generated by Django 6.0.5 on 2026-05-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shopee", "0002_color_size_category_is_active_product_gender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ім'я")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Прізвище"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("address", models.TextField(verbose_name="Адреса")),
                ("city", models.CharField(max_length=100, verbose_name="Місто")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Поштовий індекс"
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("nova_poshta", "Нова Пошта"),
                            ("ukrposhta", "Укрпошта"),
                            ("courier", "Кур'єром по місту"),
                        ],
                        default="nova_poshta",
                        max_length=20,
                        verbose_name="Спосіб доставки",
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Вартість доставки",
                    ),
                ),
                (
                    "delivery_tracking",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Трек-номер"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Готівка при отриманні"),
                            ("card", "Карткою онлайн"),
                            ("bank", "Банківський переказ"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Спосіб оплати",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплати"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сума без доставки",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Загальна сума"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "🟡 Очікує оплати"),
                            ("processing", "🔵 В обробці"),
                            ("shipped", "📦 Відправлено"),
                            ("delivered", "✅ Доставлено"),
                            ("cancelled", "❌ Скасовано"),
                            ("refunded", "🔄 Повернуто"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Коментар до замовлення"
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Коментар адміністратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Назва товару"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Кількість"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Розмір"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Колір"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Замовлення",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="shopee.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар у замовленні",
                "verbose_name_plural": "Товари в замовленні",
            },
        ),
    ]
